from io import open
from setuptools import setup

setup(name='epitran_erebus',
      version='1.25.1',
      description='Tools for transcribing languages into IPA.',
      long_description=open('README.md', encoding='utf-8').read(),
      long_description_content_type='text/markdown',
      url='https://github.com/alexanderfranca/epitran_erebus',
      download_url='https://github.com/alexanderfranca/epitran_erebus',
      author='David R. Mortensen',
      author_email='dmortens@cs.cmu.edu',
      license='MIT',
      install_requires=['setuptools',
                        'regex',
                        'panphon>=0.20',
                        'marisa-trie',
                        'requests',
                        'jamo'],
      extras_require={':python_version<"3.0"': ['subprocess32']},
      scripts=['epitran_erebus/bin/epitranscribe.py',
               'epitran_erebus/bin/uigtransliterate.py',
               'epitran_erebus/bin/detectcaps.py',
               'epitran_erebus/bin/connl2ipaspace.py',
               'epitran_erebus/bin/connl2engipaspace.py',
               'epitran_erebus/bin/migraterules.py',
               'epitran_erebus/bin/decompose.py',
               'epitran_erebus/bin/testvectorgen.py',
               'epitran_erebus/bin/transltf.py'],
      packages=['epitran_erebus'],
      package_dir={'epitran_erebus': 'epitran_erebus'},
      package_data={'epitran_erebus': ['data/*.csv', 'data/*.txt',
                                'data/map/*.csv', 'data/*.json',
                                'data/pre/*.txt', 'data/post/*.txt',
                                'data/space/*.csv', 'data/strip/*.csv',
                                'data/reromanize/*.csv',
                                'data/rules/*.txt',
                                'data/bib/*.bib']},
      zip_safe=True,
      classifiers=['Operating System :: OS Independent',
                   'Programming Language :: Python :: 3',
                   'Topic :: Software Development :: Libraries :: Python Modules',
                   'Topic :: Text Processing :: Linguistic']
      )
